graph TD

  subgraph Divorce
    Petitioner
    class Petitioner modifiedService
    Respondent
    class Respondent modifiedService
    DecreeNisi
    class DecreeNisi modifiedService
    DecreeAbsolute
    class DecreeNisi modifiedService

    CaseOrchestrator
    class CaseOrchestrator modifiedService
    CaseFormatter
    class CaseFormatter modifiedService
    CaseMaintenance
    class CaseMaintenance modifiedService
    DocGen
    class DocGen modifiedService
    EvidenceClientAPI
    DivFeesAndPay

    Petitioner-->CaseOrchestrator
    Respondent-->CaseOrchestrator
    DecreeNisi-->CaseOrchestrator
    DecreeAbsolute-->CaseOrchestrator

    CaseOrchestrator-->CaseMaintenance
    CaseOrchestrator-->CaseFormatter
    CaseOrchestrator-->DivFeesAndPay
    CaseFormatter-->CaseMaintenance
    CaseOrchestrator-->DocGen
    DocGen-->EvidenceClientAPI
  end

  subgraph IDAM
    WebFrontend
    IdamAPI
  end

  subgraph CCD
    CCDDataStore
  end

  subgraph EvidenceManagement
    Docmosis
    DocStore
  end

  subgraph RPE
    DraftStore
    SendLetterService
    ServiceAuthProvider
  end

  subgraph FeesAndPay
    Payment
    Fees
  end

  subgraph ReferenceData
    ReferenceDataAPI
  end

  subgraph GOVuk
    GovNotify
  end

  DocGen-->Docmosis
  EvidenceClientAPI-->DocStore
  CaseMaintenance-->DraftStore
  CaseMaintenance-->CCDDataStore
  CCDDataStore-.->CaseOrchestrator
  CaseOrchestrator-->Payment
  CaseOrchestrator-->SendLetterService
  CaseOrchestrator-->ReferenceDataAPI
  CaseOrchestrator-->GovNotify
  DivFeesAndPay-->Fees

  classDef newService fill:green,stroke:#333,stroke-width:4px
  classDef forkedService fill:yellow,stroke:#333,stroke-width:4px
  classDef modifiedService fill:red,stroke:#333,stroke-width:4px
